### PR TITLE
Add additional args to docker call in build-push-ecr

### PR DESCRIPTION
**Pull request by phildarnowsky**
As discussed in https://github.com/mbta/skate/pull/1139

### CODE REVIEW

**Comment by phildarnowsky** [comment]
@paulswartz @ianwestcott I tagged you both in as reviewers here, who's the best person to ask going forward?

Also, is there anything analogous to `terraform validate` that you can use as a quick syntax/sanity check on actions?

**Comment by paulswartz** [comment]
You can use ’mbta/actions@branch-name' in the Skate action to test that it works properly. I'll look into a YAML validator action for this repo.

**Comment by phildarnowsky** [comment]
@paulswartz @ianwestcott it looks like, while the Skate action as a whole isn't working yet, the part that uses these args is working, so I'm going to merge.

**Comment by paulswartz** [comment]
@phildarnowsky can you also retag v1 and tag a new point release?

**Comment by phildarnowsky** [comment]
@paulswartz I'm about to push a small correction to make yamllint pass, will tag that

**Pull request merged**
